# -*- coding: utf-8 -*-
"""Fine_tuning_bert_base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROmTH0k4iOLzFcuScAVNR28I6AV95z97
"""

!pip install huggingface_hub
!huggingface-cli login
#!huggingface-cli repo create ner_model_bert_base

!pip install datasets
!pip install transformers[torch]

import pandas as pd
import numpy as np
import torch
import random
import ast
from datasets import Dataset, DatasetDict, Features, Sequence, ClassLabel, Value
from transformers import AutoTokenizer, AutoModelForTokenClassification, DataCollatorForTokenClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Establecer semilla aleatoria para la reproducibilidad

# Ruta al archivo CSV
csv_path = "/content/drive/MyDrive/Colab Notebooks/etiquetado.csv"

# Cargar DataFrame desde el archivo CSV y convertirlo a dict
pd_df = pd.read_csv(csv_path)

# Convertir las columnas 'tokens' y 'ner_tags' de cadenas a listas
pd_df['tokens'] = pd_df['tokens'].apply(ast.literal_eval)
pd_df['ner_tags'] = pd_df['ner_tags'].apply(ast.literal_eval)

dict_corpus = pd_df.to_dict(orient='list')

# Solución 1: Agregar 'TRA_ID' a features
features = Features({
    'tokens': Sequence(Value('string')),
    'ner_tags': Sequence(ClassLabel(names=["O", "B-PER", "I-PER", "B-LOC", "I-LOC"])),
})

del dict_corpus['TRA_ID']

# Convertir el corpus a Dataset de la biblioteca `datasets`
dataset = Dataset.from_dict(dict_corpus, features=features)

# Dividir el dataset en entrenamiento (80%), validación (10%) y testeo (10%)
train_valid_test_split = dataset.train_test_split(test_size=0.2)
valid_test_split = train_valid_test_split["test"].train_test_split(test_size=0.5)
dataset = DatasetDict({
    'train': train_valid_test_split['train'],
    'validation': valid_test_split['train'],
    'test': valid_test_split['test']
})

# Cargar el modelo y el tokenizador
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tokenizer = AutoTokenizer.from_pretrained("dccuchile/bert-base-spanish-wwm-cased")
model = AutoModelForTokenClassification.from_pretrained("dccuchile/bert-base-spanish-wwm-cased",
    num_labels=len(dataset['train'].features['ner_tags'].feature.names),
    ignore_mismatched_sizes=True
).to(device)

# Obtener la longitud máxima permitida por el modelo
max_length = tokenizer.model_max_length

# Función para tokenizar y alinear etiquetas
def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        padding='max_length',  # Asegura el padding al largo máximo permitido por el modelo
        max_length=max_length,
        is_split_into_words=True
    )
    labels = []
    for i, label in enumerate(examples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx
        # Ajustar etiquetas a max_length
        if len(label_ids) < max_length:
            label_ids.extend([-100] * (max_length - len(label_ids)))
        else:
            label_ids = label_ids[:max_length]
        labels.append(label_ids)
    tokenized_inputs["labels"] = labels
    return tokenized_inputs

# Tokenizar el dataset
tokenized_dataset = dataset.map(tokenize_and_align_labels, batched=True)

# Crear el Data Collator
data_collator = DataCollatorForTokenClassification(
    tokenizer,
    padding='max_length',
    max_length=max_length
)

# Parámetros de entrenamiento
training_args = TrainingArguments(
    output_dir="./results1",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
    save_strategy="epoch",
    load_best_model_at_end=True
)

# Métricas de evaluación
def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    # Flatten the lists
    true_labels = [dataset['train'].features['ner_tags'].feature.names[l] for label in labels for l in label if l != -100]
    true_predictions = [dataset['train'].features['ner_tags'].feature.names[p] for prediction, label in zip(predictions, labels) for p, l in zip(prediction, label) if l != -100]

    precision, recall, f1, _ = precision_recall_fscore_support(true_labels, true_predictions, labels=dataset['train'].features['ner_tags'].feature.names, average='macro', zero_division=0)
    accuracy = accuracy_score(true_labels, true_predictions)

    return {
        "accuracy": accuracy,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

# Configuración del entrenador
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

# Entrenar el modelo
trainer.train()

# Evaluar el modelo en el conjunto de validación
validation_results = trainer.evaluate()
print("Resultados de Validación:", validation_results)

# Evaluar el modelo en el conjunto de prueba
test_results = trainer.evaluate(tokenized_dataset["test"])
print("Resultados de Prueba:", test_results)

# Guardar el modelo
model.save_pretrained("./ner_model_bert_base")
tokenizer.save_pretrained("./ner_model_bert_base")

model.push_to_hub("ner_model_bert_base")
tokenizer.push_to_hub("ner_model_bert_base")



# Función para predecir entidades distintas de 'O'
def predict_non_O_entities(dataset, tokenizer, model, label_list, device):
    results = []
    softmax = torch.nn.Softmax(dim=-1)
    for example in dataset:
        tokens = example["tokens"]
        inputs = tokenizer(tokens, padding='max_length', truncation=True, return_tensors="pt", is_split_into_words=True)
        inputs = {key: value.to(device) for key, value in inputs.items()}
        with torch.no_grad():
            logits = model(**inputs).logits
        logits = logits[0].cpu().numpy()

        probabilities = softmax(torch.from_numpy(logits))
        scores = np.max(probabilities.numpy(), axis=-1)

        predictions = np.argmax(logits, axis=-1)
        predicted_labels = [label_list[p] for p in predictions[:len(tokens)]]
        predicted_scores = scores[:len(tokens)]

        result = []
        for token, label, score in zip(tokens, predicted_labels, predicted_scores):
            if label != "O":
                result.append({
                    "token": token,
                    "label": label,
                    "score": score
                })
        if result:
            results.append(result)
    return results

# Obtener predicciones con puntajes para entidades distintas de 'O' en el conjunto de prueba
predictions_non_O = predict_non_O_entities(tokenized_dataset["test"], tokenizer, model, dataset['train'].features['ner_tags'].feature.names, device)

# Mostrar predicciones detalladas para entidades distintas de 'O'
for example in predictions_non_O[:3]:  # Mostrar los primeros 3 ejemplos
    for token_info in example:
        print(f"Entidad: {token_info['token']}, Tipo: {token_info['label']}, Score: {token_info['score']:.4f}")
    print()

# prompt: : Using the `Trainer` with `PyTorch` requires `accelerate>=0.21.0`: Please run `pip install transformers[torch]` or `pip install accelerate -U`

!pip install datasets
!pip install transformers[torch]