# -*- coding: utf-8 -*-
"""modelo_bert_base_FT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GzxceU6GFRmZOlc8ZF7hunwaEigMifJ
"""

import time
import pandas as pd
from transformers import AutoTokenizer, AutoModelForTokenClassification
import requests

tokenizer = AutoTokenizer.from_pretrained("dannyLeo16/ner_model_bert_base")
model = AutoModelForTokenClassification.from_pretrained("dannyLeo16/ner_model_bert_base")

import requests
API_URL = "https://api-inference.huggingface.co/models/dannyLeo16/ner_model_bert_base"
headers = {"Authorization": "Bearer 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"}

start_time= time.time()
def query(payload):
    response = requests.post(API_URL, headers=headers, json=payload)
    if response.status_code == 200:
        return response.json()
    else:
        # Manejar la situación en la que la API no devuelve una respuesta exitosa
        print(f"Error en la API: {response.status_code}")
        return []

# Carga el archivo csv
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/prueba_modelos_10.csv')

# Variable para contar el total de entidades nombradas
total_entidades_nombradas = 0

# Itera sobre cada fila del dataframe
for index, row in df.iterrows():
    # Realiza la consulta
    output = query({"inputs": row['ATA_TEXTO']})

    # Verifica que 'output' sea una lista antes de continuar
    if isinstance(output, list):
        # Filtra los resultados para excluir entidades con 'LABEL_0'
        filtered_output = [entity for entity in output if entity['entity_group'] != 'LABEL_0']

        # Imprime el ID de la llamada y las entidades nombradas que no tienen 'LABEL_0'
        print(f"ID LLAMADA: {row['TRA_ID']}")
        for entity in filtered_output:
            print(f"entidad: {entity['word']}, tipo: {entity['entity_group']}, score: {entity['score']}")

        # Imprime el número de entidades encontradas
        print(f"Entidades encontradas: {len(filtered_output)}")

        # Suma al total de entidades nombradas
        total_entidades_nombradas += len(filtered_output)
    else:
        print(f"La respuesta no es una lista: {output}")

model.num_parameters()

# Imprime el total de entidades nombradas al final del bucle
print(f"Total de entidades nombradas: {total_entidades_nombradas}")

end_time = time.time()
execution_time = end_time - start_time
print(f"Tiempo de ejecución: {execution_time} segundos")

# Imprime el número de parámetros del modelo y su descripción
print(f"Número de parámetros del modelo: {model.num_parameters()}")

# Imprime la huella de memoria del modelo y su descripción
print(f"Huella de memoria del modelo: {model.get_memory_footprint()}")

# Imprime la longitud del tokenizer y su descripción
print(f"Longitud del tokenizer: {len(tokenizer)} tokens")

import pandas as pd
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline
from tqdm import tqdm

# Cargar modelo y tokenizer localmente
model_name = "dannyLeo16/ner_model_bert_base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

# Crear pipeline para NER
ner_pipeline = pipeline("ner", model=model, tokenizer=tokenizer, aggregation_strategy="simple")

# Leer archivo procesado (el que generamos con los textos del alertante)
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado.csv')

# Lista para almacenar entidades extraídas
entidades_extraidas = []

# Procesar cada fila
for _, row in tqdm(df.iterrows(), total=len(df)):
    id_llamada = row['TRA_ID']
    texto = row['TEXTO_ALERTANTE']

    # Obtener entidades con el pipeline
    try:
        resultado = ner_pipeline(texto)
    except Exception as e:
        print(f"Error en llamada {id_llamada}: {e}")
        continue

    for entidad in resultado:
        entidades_extraidas.append({
            "TRA_ID": id_llamada,
            "palabra": entidad['word'],
            "etiqueta": entidad['entity_group'],
            "score": entidad['score']
        })

# Crear DataFrame final y guardar
df_entidades = pd.DataFrame(entidades_extraidas)
df_entidades.to_csv('/content/drive/MyDrive/Colab Notebooks/entidades_detectadas.csv', index=False)

print("✔️ Entidades guardadas en 'entidades_detectadas.csv'")



import pandas as pd

# === 1. Cargar los archivos CSV ===
texto_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado.csv')
entidades_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/entidades_detectadas.csv')

# === 2. Detectar si hay personas o ubicaciones por llamada ===
def tiene_label(df, labels):
    return df['etiqueta'].isin(labels).any()

agrupado = entidades_df.groupby("TRA_ID").apply(lambda x: pd.Series({
    "TienePersona": int(tiene_label(x, ['LABEL_1', 'LABEL_2'])),
    "TieneUbicacion": int(tiene_label(x, ['LABEL_3', 'LABEL_4']))
})).reset_index()

# === 3. Unir con el texto original por TRA_ID ===
df_completo = pd.merge(texto_df, agrupado, on="TRA_ID", how="left")
df_completo.fillna({"TienePersona": 0, "TieneUbicacion": 0}, inplace=True)

# === 4. Lista ampliada de palabras clave y tipos de emergencia ===
palabras_emergencia = {
    # Delitos
    "robo": "Delito", "robaron": "Delito", "asaltaron": "Delito", "asalto": "Delito", "ladron": "Delito",
    "sospechoso": "Delito", "delincuente": "Delito", "intento de robo": "Delito",

    # Violencia
    "pelea": "Violenta", "peleando": "Violenta", "golpearon": "Violenta", "gritos": "Violenta",
    "gritando": "Violenta", "lo están matando": "Violenta", "amenaza": "Violenta",

    # Médicas
    "herido": "Médica", "herida": "Médica", "sangre": "Médica", "caída": "Médica", "se cayó": "Médica",
    "accidente": "Médica", "inconsciente": "Médica", "desmayado": "Médica",

    # Incendios
    "fuego": "Incendio", "incendio": "Incendio", "humo": "Incendio", "quemando": "Incendio",

    # Accidentes viales
    "choque": "Accidente", "colisión": "Accidente", "atropello": "Accidente", "chocaron": "Accidente",

    # Otros
    "arma": "Violenta", "arma blanca": "Violenta", "pistola": "Violenta"
}

def detectar_palabra_clave(texto):
    texto = str(texto).lower()
    for palabra, tipo in palabras_emergencia.items():
        if palabra in texto:
            return palabra, tipo
    return "ninguna", "No clasificado"

df_completo[["PalabraClave", "TipoEmergencia"]] = df_completo["TEXTO_ALERTANTE"].apply(
    detectar_palabra_clave
).apply(pd.Series)

# === 5. Guardar el resultado final ===
df_completo.to_csv('/content/drive/MyDrive/Colab Notebooks/dataset_estructurado_para_mineria.csv', index=False)
print("✔️ Dataset estructurado guardado como 'dataset_estructurado_para_mineria.csv'")

!pip install owlready2

import pandas as pd
from owlready2 import *

# Cargar el dataset estructurado
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset_estructurado_para_mineria.csv")

# Crear la ontología
onto = get_ontology("http://www.ecu911.org/ontologia_completa.owl")

with onto:
    # Clases
    class LlamadaEmergencia(Thing): pass
    class Persona(Thing): pass
    class Ubicacion(Thing): pass

    # Propiedades de objeto
    class reportadoPor(ObjectProperty):
        domain = [LlamadaEmergencia]
        range = [Persona]

    class ocurreEn(ObjectProperty):
        domain = [LlamadaEmergencia]
        range = [Ubicacion]

    # Propiedades de datos
    class tieneTipo(DataProperty):
        domain = [LlamadaEmergencia]
        range = [str]

    class tieneClave(DataProperty):
        domain = [LlamadaEmergencia]
        range = [str]

# Crear instancias a partir del dataset
for _, row in df.iterrows():
    llamada_id = f"Llamada_{int(row['TRA_ID'])}"
    llamada = onto.LlamadaEmergencia(llamada_id)

    # Asignar propiedades de datos como listas (para evitar el error)
    llamada.tieneTipo = [str(row['TipoEmergencia'])]
    llamada.tieneClave = [str(row['INCIDENTE'])]

    # Relaciones con persona
    if row["TienePersona"] == 1:
        persona = onto.Persona(f"Persona_{int(row['TRA_ID'])}")
        llamada.reportadoPor.append(persona)

    # Relaciones con ubicación
    if row["TieneUbicacion"] == 1:
        ubicacion = onto.Ubicacion(f"Ubicacion_{int(row['TRA_ID'])}")
        llamada.ocurreEn.append(ubicacion)



# Guardar archivo .owl
onto.save(file="/content/drive/MyDrive/Colab Notebooks/ecu911_completo.owl", format="rdfxml")
print("✅ Ontología completa generada como: /content/ecu911_completo.owl")

import pandas as pd

# === 1. Cargar los archivos CSV ===
texto_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado.csv')
entidades_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/entidades_detectadas.csv')

# === 2. Detectar si hay personas o ubicaciones por llamada ===
def tiene_label(df, labels):
    return df['etiqueta'].isin(labels).any()

agrupado = entidades_df.groupby("TRA_ID").apply(lambda x: pd.Series({
    "TienePersona": int(tiene_label(x, ['LABEL_1', 'LABEL_2'])),
    "TieneUbicacion": int(tiene_label(x, ['LABEL_3', 'LABEL_4']))
})).reset_index()

# === 3. Unir con el texto original por TRA_ID ===
df_completo = pd.merge(texto_df, agrupado, on="TRA_ID", how="left")
df_completo.fillna({"TienePersona": 0, "TieneUbicacion": 0}, inplace=True)

# === 4. Lista ampliada de palabras clave y tipos de emergencia ===
palabras_emergencia = {
    # Delitos
    "robo": "Delito", "robaron": "Delito", "asaltaron": "Delito", "asalto": "Delito", "ladron": "Delito",
    "sospechoso": "Delito", "delincuente": "Delito", "intento de robo": "Delito",

    # Violencia
    "pelea": "Violenta", "peleando": "Violenta", "golpearon": "Violenta", "gritos": "Violenta",
    "gritando": "Violenta", "lo están matando": "Violenta", "amenaza": "Violenta",

    # Médicas
    "herido": "Médica", "herida": "Médica", "sangre": "Médica", "caída": "Médica", "se cayó": "Médica",
    "accidente": "Médica", "inconsciente": "Médica", "desmayado": "Médica",

    # Incendios
    "fuego": "Incendio", "incendio": "Incendio", "humo": "Incendio", "quemando": "Incendio",

    # Accidentes viales
    "choque": "Accidente", "colisión": "Accidente", "atropello": "Accidente", "chocaron": "Accidente",

    # Otros
    "arma": "Violenta", "arma blanca": "Violenta", "pistola": "Violenta"
}

def detectar_palabra_clave(texto):
    texto = str(texto).lower()
    for palabra, tipo in palabras_emergencia.items():
        if palabra in texto:
            return palabra, tipo
    return "ninguna", "No clasificado"

df_completo[["PalabraClave", "TipoEmergencia"]] = df_completo["TEXTO_ALERTANTE"].apply(
    detectar_palabra_clave
).apply(pd.Series)

# === 5. Agregar nombres de entidades detectadas (PERSONAS y UBICACIONES) ===
entidades_df["palabra"] = entidades_df["palabra"].astype(str).fillna("")

# PERSONAS
personas = entidades_df[entidades_df["etiqueta"].isin(["LABEL_1", "LABEL_2"])]
personas_grouped = (
    personas.groupby("TRA_ID")["palabra"]
    .apply(lambda x: " ".join(sorted(set(x), key=x.tolist().index)))
    .reset_index()
    .rename(columns={"palabra": "NombrePersona"})
)

# UBICACIONES
ubicaciones = entidades_df[entidades_df["etiqueta"].isin(["LABEL_3", "LABEL_4"])]
ubicaciones_grouped = (
    ubicaciones.groupby("TRA_ID")["palabra"]
    .apply(lambda x: " ".join(sorted(set(x), key=x.tolist().index)))
    .reset_index()
    .rename(columns={"palabra": "NombreUbicacion"})
)

# Unir al dataframe completo
df_completo = df_completo.merge(personas_grouped, on="TRA_ID", how="left")
df_completo = df_completo.merge(ubicaciones_grouped, on="TRA_ID", how="left")
df_completo[["NombrePersona", "NombreUbicacion"]] = df_completo[["NombrePersona", "NombreUbicacion"]].fillna("")

# === 6. Guardar el resultado final enriquecido ===
df_completo.to_csv('/content/drive/MyDrive/Colab Notebooks/dataset_estructurado_para_mineria.csv', index=False)
print("✔️ Dataset enriquecido guardado como 'dataset_estructurado_para_mineria.csv'")

import pandas as pd

# Cargar entidades
entidades = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/entidades_detectadas.csv')

# Convertir todo a texto, eliminar NaN
entidades["palabra"] = entidades["palabra"].astype(str).fillna("")

# Función para limpiar y quedarte solo con una frase representativa
def construir_nombre(df):
    # Ordena según aparición y quita duplicados (mantiene orden original)
    palabras = df["palabra"].tolist()
    palabras_unicas = []
    for p in palabras:
        if p not in palabras_unicas:
            palabras_unicas.append(p)
    return " ".join(palabras_unicas)

# PERSONAS
personas = entidades[entidades["etiqueta"].isin(["LABEL_1", "LABEL_2"])]
nombres_persona = personas.groupby("TRA_ID").apply(construir_nombre).reset_index()
nombres_persona.columns = ["TRA_ID", "NombrePersona"]

# UBICACIONES
ubicaciones = entidades[entidades["etiqueta"].isin(["LABEL_3", "LABEL_4"])]
nombres_ubicacion = ubicaciones.groupby("TRA_ID").apply(construir_nombre).reset_index()
nombres_ubicacion.columns = ["TRA_ID", "NombreUbicacion"]

# GUARDAR
nombres_persona.to_csv("/content/drive/MyDrive/Colab Notebooks/nombres_personas_limpio.csv", index=False)
nombres_ubicacion.to_csv("/content/drive/MyDrive/Colab Notebooks/nombres_ubicaciones_limpio.csv", index=False)
print("✔️ Archivos 'nombres_personas_limpio.csv' y 'nombres_ubicaciones_limpio.csv' generados.")

# === MONTAR DRIVE ===


# === IMPORTAR LIBRERÍAS ===
import pandas as pd

# === CARGAR LOS ARCHIVOS ===
entidades = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/entidades_detectadas.csv')
texto_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado.csv')

# === ETAPA 1: DETECTAR PERSONAS Y UBICACIONES ===
def tiene_label(df, labels):
    return df['etiqueta'].isin(labels).any()

agrupado = entidades.groupby("TRA_ID").apply(lambda x: pd.Series({
    "TienePersona": int(tiene_label(x, ['LABEL_1', 'LABEL_2'])),
    "TieneUbicacion": int(tiene_label(x, ['LABEL_3', 'LABEL_4']))
})).reset_index()

# === ETAPA 2: DETECTAR PALABRAS CLAVE Y TIPO DE EMERGENCIA ===
palabras_emergencia = {
    # === DELITO ===
    "robo": "Delito", "robaron": "Delito", "asaltaron": "Delito", "asalto": "Delito", "hurtaron": "Delito",
    "ladron": "Delito", "ladrones": "Delito", "delincuente": "Delito", "me quitaron": "Delito",
    "intento de robo": "Delito", "se llevaron": "Delito", "cartera": "Delito", "carro robado": "Delito",
    "robar": "Delito", "entraron a robar": "Delito",

    # === VIOLENCIA ===
    "gritos": "Violenta", "gritando": "Violenta", "pelea": "Violenta", "peleando": "Violenta",
    "golpearon": "Violenta", "amenaza": "Violenta", "lo están matando": "Violenta", "agresión": "Violenta",
    "lo golpearon": "Violenta", "dispararon": "Violenta", "lo están golpeando": "Violenta",
    "forcejeo": "Violenta", "violencia": "Violenta", "conflicto": "Violenta",

    # === MÉDICAS ===
    "herido": "Médica", "herida": "Médica", "sangre": "Médica", "desmayado": "Médica",
    "inconsciente": "Médica", "convulsiona": "Médica", "accidente": "Médica", "se cayó": "Médica",
    "caída": "Médica", "se lastimó": "Médica", "fractura": "Médica", "dolor fuerte": "Médica",
    "accidente doméstico": "Médica", "persona mal": "Médica", "no respira": "Médica",
    "paro cardíaco": "Médica",

    # === INCENDIOS ===
    "fuego": "Incendio", "incendio": "Incendio", "humo": "Incendio", "quemando": "Incendio",
    "quemadura": "Incendio", "chispa": "Incendio", "explosión": "Incendio", "se quema": "Incendio",
    "gas": "Incendio", "fuga de gas": "Incendio", "llamas": "Incendio",

    # === ACCIDENTES VIALES ===
    "choque": "Accidente", "colisión": "Accidente", "atropello": "Accidente", "accidente de tránsito": "Accidente",
    "chocaron": "Accidente", "auto volcado": "Accidente", "carro estrellado": "Accidente", "motociclista caído": "Accidente",
    "vehículo accidentado": "Accidente", "bicicleta accidentada": "Accidente", "persona atropellada": "Accidente",

    # === ARMAS ===
    "arma": "Violenta", "arma blanca": "Violenta", "arma de fuego": "Violenta", "pistola": "Violenta",
    "cuchillo": "Violenta", "revolver": "Violenta", "fusil": "Violenta", "machete": "Violenta"

}


def detectar_palabra_clave(texto):
    texto = str(texto).lower()
    for palabra, tipo in palabras_emergencia.items():
        if palabra in texto:
            return palabra, tipo
    return "ninguna", "No clasificado"

texto_df[["PalabraClave", "TipoEmergencia"]] = texto_df["TEXTO_ALERTANTE"].apply(
    detectar_palabra_clave
).apply(pd.Series)

# === ETAPA 3: CONSTRUIR NOMBRES LIMPIOS ===
def construir_nombre(df):
    palabras = df["palabra"].astype(str).fillna("").tolist()
    palabras_unicas = []
    for p in palabras:
        if p not in palabras_unicas:
            palabras_unicas.append(p)
    return " ".join(palabras_unicas)

def reconstruir_tokens(palabras):
    resultado = ""
    for token in palabras:
        if token.startswith("##"):
            resultado += token[2:]
        else:
            if resultado:
                resultado += " "
            resultado += token
    return resultado

# PERSONAS
personas = entidades[entidades["etiqueta"].isin(["LABEL_1", "LABEL_2"])]
nombres_persona = personas.groupby("TRA_ID").apply(construir_nombre).reset_index()
nombres_persona.columns = ["TRA_ID", "NombrePersona"]
nombres_persona["NombrePersona"] = nombres_persona["NombrePersona"].apply(lambda t: reconstruir_tokens(t.split()))

# UBICACIONES
ubicaciones = entidades[entidades["etiqueta"].isin(["LABEL_3", "LABEL_4"])]
nombres_ubicacion = ubicaciones.groupby("TRA_ID").apply(construir_nombre).reset_index()
nombres_ubicacion.columns = ["TRA_ID", "NombreUbicacion"]
nombres_ubicacion["NombreUbicacion"] = nombres_ubicacion["NombreUbicacion"].apply(lambda t: reconstruir_tokens(t.split()))

# === ETAPA 4: UNIFICAR TODO ===
df_completo = texto_df.merge(agrupado, on="TRA_ID", how="left")
df_completo = df_completo.merge(nombres_persona, on="TRA_ID", how="left")
df_completo = df_completo.merge(nombres_ubicacion, on="TRA_ID", how="left")
df_completo.fillna({"TienePersona": 0, "TieneUbicacion": 0, "NombrePersona": "", "NombreUbicacion": ""}, inplace=True)

# === ETAPA 5: GUARDAR CSV FINAL EN DRIVE ===
output_path = '/content/drive/MyDrive/Colab Notebooks/dataset_estructurado_limpio.csv'
df_completo.to_csv(output_path, index=False)
print(f"✔️ Dataset final guardado en: {output_path}")

# Paso 1: Librerías
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.preprocessing import LabelEncoder

# Paso 2: Cargar datasets
df_texto = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado.csv')
df_entidades = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/entidades_detectadas.csv')

# Paso 3: Reconstrucción de nombres y ubicaciones
df_entidades["palabra"] = df_entidades["palabra"].astype(str).fillna("")

def reconstruir_frase(df):
    palabras = df["palabra"].tolist()
    frase = []
    for p in palabras:
        if not p.startswith("##"):
            frase.append(p)
        else:
            if frase:
                frase[-1] += p[2:]
            else:
                frase.append(p[2:])
    return " ".join(frase)

# Nombres
df_personas = df_entidades[df_entidades["etiqueta"].isin(["LABEL_1", "LABEL_2"])]
nombres_persona = df_personas.groupby("TRA_ID").apply(reconstruir_frase).reset_index()
nombres_persona.columns = ["TRA_ID", "NombrePersona"]

# Ubicaciones
df_ubicaciones = df_entidades[df_entidades["etiqueta"].isin(["LABEL_3", "LABEL_4"])]
nombres_ubicacion = df_ubicaciones.groupby("TRA_ID").apply(reconstruir_frase).reset_index()
nombres_ubicacion.columns = ["TRA_ID", "NombreUbicacion"]

# Paso 4: Marcadores binarios
def tiene_label(df, etiquetas):
    return df["etiqueta"].isin(etiquetas).any()

agrupado = df_entidades.groupby("TRA_ID").apply(lambda x: pd.Series({
    "TienePersona": int(tiene_label(x, ['LABEL_1', 'LABEL_2'])),
    "TieneUbicacion": int(tiene_label(x, ['LABEL_3', 'LABEL_4']))
})).reset_index()

# Paso 5: Unificación
df_completo = pd.merge(df_texto, agrupado, on="TRA_ID", how="left")
df_completo = pd.merge(df_completo, nombres_persona, on="TRA_ID", how="left")
df_completo = pd.merge(df_completo, nombres_ubicacion, on="TRA_ID", how="left")
df_completo.fillna({"TienePersona": 0, "TieneUbicacion": 0}, inplace=True)

# Paso 6: Banco de palabras clave y tipo de emergencia
palabras_emergencia = {
    # Delitos
    "robo": "Delito", "asaltaron": "Delito", "asalto": "Delito", "hurto": "Delito", "intento de robo": "Delito",
    "ladron": "Delito", "ladrones": "Delito", "sospechoso": "Delito", "delincuente": "Delito", "allanamiento": "Delito",
    "robaron": "Delito", "estafa": "Delito", "extorsión": "Delito",

    # Violencia o conflictos
    "pelea": "Violenta", "peleando": "Violenta", "golpearon": "Violenta", "gritos": "Violenta", "gritando": "Violenta",
    "lo están matando": "Violenta", "amenaza": "Violenta", "agresión": "Violenta", "disputa": "Violenta",
    "acoso": "Violenta", "violencia doméstica": "Violenta",

    # Médicas
    "herido": "Médica", "herida": "Médica", "sangre": "Médica", "caída": "Médica", "se cayó": "Médica",
    "inconsciente": "Médica", "desmayado": "Médica", "infarto": "Médica", "dolor": "Médica", "emergencia médica": "Médica",
    "ataque": "Médica", "convulsión": "Médica", "mareado": "Médica", "enfermo": "Médica",

    # Incendios
    "fuego": "Incendio", "incendio": "Incendio", "humo": "Incendio", "quemando": "Incendio", "explosión": "Incendio",
    "gas": "Incendio", "chispas": "Incendio",

    # Accidentes viales
    "choque": "Accidente", "colisión": "Accidente", "atropello": "Accidente", "chocaron": "Accidente",
    "accidente": "Accidente", "volcó": "Accidente", "despiste": "Accidente",

    # Armas
    "arma": "Violenta", "arma blanca": "Violenta", "pistola": "Violenta", "cuchillo": "Violenta", "machete": "Violenta",

    # Otros posibles
    "secuestro": "Delito", "desaparición": "Delito", "perdido": "Otros", "ruido": "Otros", "problema": "Otros"
}



def detectar_palabra_clave(texto):
    texto = str(texto).lower()
    for palabra, tipo in palabras_emergencia.items():
        if palabra in texto:
            return palabra, tipo
    return "ninguna", "No clasificado"

df_completo[["PalabraClave", "TipoEmergencia"]] = df_completo["TEXTO_ALERTANTE"].apply(detectar_palabra_clave).apply(pd.Series)

# Paso 7: Asignar clave de emergencia
mapa_claves = {
    "Delito": "CLAVE ROJA",
    "Violenta": "CLAVE ROJA",
    "Médica": "CLAVE AMARILLA",
    "Incendio": "CLAVE NARANJA",
    "Accidente": "CLAVE NARANJA",
    "No clasificado": "CLAVE VERDE"
}
df_completo["ClaveEmergencia"] = df_completo["TipoEmergencia"].map(mapa_claves).fillna("CLAVE VERDE")

# Paso 8: Entrenar árbol de decisión
le_palabra = LabelEncoder()
le_clave = LabelEncoder()
df_completo["PalabraClaveCod"] = le_palabra.fit_transform(df_completo["PalabraClave"].astype(str))
df_completo["ClaveEmergenciaCod"] = le_clave.fit_transform(df_completo["ClaveEmergencia"].astype(str))

X = df_completo[["TienePersona", "TieneUbicacion", "PalabraClaveCod"]]
y = df_completo["ClaveEmergenciaCod"]

arbol = DecisionTreeClassifier(max_depth=4, random_state=42)
arbol.fit(X, y)

# Paso 9: Exportar reglas
clase_nombre = {i: nombre for i, nombre in enumerate(le_clave.classes_)}
reglas_texto = export_text(arbol, feature_names=list(X.columns))
reglas_decodificadas = []
for linea in reglas_texto.split("\n"):
    if "class:" in linea:
        clase_cod = int(linea.strip().split("class: ")[-1])
        clase_desc = clase_nombre.get(clase_cod, "Desconocido")
        linea = linea.replace(f"class: {clase_cod}", f"CLAVE: {clase_desc}")
    reglas_decodificadas.append(linea)

print("=== Reglas del árbol de decisión ===")
for regla in reglas_decodificadas:
    print(regla)

# Paso 10: Guardar CSV final
df_completo.to_csv('/content/drive/MyDrive/Colab Notebooks/dataset_final_estructurado_1.csv', index=False)
print("✔️ Dataset exportado como 'dataset_final_estructurado.csv'")

# Paso 1: Instalar librerías necesarias
!pip install transformers --quiet

# Paso 2: Importar librerías
import pandas as pd
from transformers import pipeline

# Paso 3: Cargar dataset
df_alertas = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado.csv')

# Paso 4: Inicializar modelo zero-shot
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Paso 5: Definir etiquetas
labels = [
    "Accidente de tránsito",
    "Violencia doméstica",
    "Asalto",
    "Robo",
    "Emergencia médica",
    "Incendio",
    "Persona herida",
    "Secuestro",
    "Amenaza con arma",
    "Pelea callejera" ,
    "Emergencia no clasificada",
]

# Paso 6: Función para clasificar texto
def clasificar_emergencia(texto):
    if not isinstance(texto, str) or texto.strip() == "":
        return "No clasificado"
    result = classifier(texto, candidate_labels=labels)
    return result["labels"][0]  # devuelve la clase con mayor score

# Paso 7: Aplicar clasificación a cada fila
df_alertas["TipoEmergencia"] = df_alertas["TEXTO_ALERTANTE"].apply(clasificar_emergencia)

# Paso final: Guardar dataset con predicciones
df_alertas.to_csv('/content/drive/MyDrive/Colab Notebooks/dataset_con_emergencias_zero_shot.csv', index=False)
print("✔️ Dataset guardado como 'dataset_con_emergencias_zero_shot.csv'")





# Paso 1: Librerías
import pandas as pd

# Paso 2: Cargar archivos
df_texto = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado_1.csv')
df_entidades = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/entidades_detectadas.csv')
df_emergencias = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset_con_emergencias_zero_shot.csv')

# Paso 3: Reconstrucción de nombres y ubicaciones
df_entidades["palabra"] = df_entidades["palabra"].astype(str).fillna("")

def reconstruir_frase(df):
    palabras = df["palabra"].tolist()
    frase = []
    for p in palabras:
        if not p.startswith("##"):
            frase.append(p)
        else:
            if frase:
                frase[-1] += p[2:]
            else:
                frase.append(p[2:])
    return " ".join(frase)

# Nombres
df_personas = df_entidades[df_entidades["etiqueta"].isin(["LABEL_1", "LABEL_2"])]
nombres_persona = df_personas.groupby("TRA_ID").apply(reconstruir_frase).reset_index()
nombres_persona.columns = ["TRA_ID", "NombrePersona"]

# Ubicaciones
df_ubicaciones = df_entidades[df_entidades["etiqueta"].isin(["LABEL_3", "LABEL_4"])]
nombres_ubicacion = df_ubicaciones.groupby("TRA_ID").apply(reconstruir_frase).reset_index()
nombres_ubicacion.columns = ["TRA_ID", "NombreUbicacion"]

# 1. Filtrar nombres de personas antes de unir al dataframe principal
nombres_persona["NombrePersona"] = nombres_persona["NombrePersona"].apply(
    lambda x: x if isinstance(x, str) and len(x.replace(" ", "")) >= 4 else ""
)

# 2. Filtrar ubicaciones también antes de la unión
nombres_ubicacion["NombreUbicacion"] = nombres_ubicacion["NombreUbicacion"].apply(
    lambda x: x if isinstance(x, str) and len(x.replace(" ", "")) >= 4 else ""
)

# Marcadores binarios
def tiene_label(df, etiquetas):
    return df["etiqueta"].isin(etiquetas).any()

agrupado = df_entidades.groupby("TRA_ID").apply(lambda x: pd.Series({
    "TienePersona": int(tiene_label(x, ['LABEL_1', 'LABEL_2'])),
    "TieneUbicacion": int(tiene_label(x, ['LABEL_3', 'LABEL_4']))
})).reset_index()

# Unificar todo
df_completo = df_texto.merge(agrupado, on="TRA_ID", how="left")
df_completo = df_completo.merge(nombres_persona, on="TRA_ID", how="left")
df_completo = df_completo.merge(nombres_ubicacion, on="TRA_ID", how="left")
df_completo = df_completo.merge(df_emergencias[["TRA_ID", "TipoEmergencia"]], on="TRA_ID", how="left")
df_completo.fillna({"TienePersona": 0, "TieneUbicacion": 0}, inplace=True)

# Asignar clave de emergencia
mapa_claves = {
    # CLAVE ROJA
    "Robo": "CLAVE ROJA", "Asalto": "CLAVE ROJA", "Allanamiento": "CLAVE ROJA",
    "Estafa": "CLAVE ROJA", "Secuestro": "CLAVE ROJA",
    "Pelea": "CLAVE ROJA", "Violencia doméstica": "CLAVE ROJA", "Agresión física": "CLAVE ROJA", "Amenaza": "CLAVE ROJA",

    # CLAVE AMARILLA
    "Persona herida": "CLAVE AMARILLA", "Infarto": "CLAVE AMARILLA", "Desmayo": "CLAVE AMARILLA",
    "Convulsión": "CLAVE AMARILLA", "Persona inconsciente": "CLAVE AMARILLA",

    # CLAVE NARANJA
    "Incendio": "CLAVE NARANJA", "Explosión": "CLAVE NARANJA", "Fuga de gas": "CLAVE NARANJA",
    "Humo": "CLAVE NARANJA", "Corto circuito": "CLAVE NARANJA",
    "Choque": "CLAVE NARANJA", "Atropello": "CLAVE NARANJA", "Accidente de tránsito": "CLAVE NARANJA", "Colisión": "CLAVE NARANJA",

    # CLAVE VERDE
    "Emergencia no clasificada": "CLAVE VERDE", "Emergencia menor": "CLAVE VERDE",
    "Ruido": "CLAVE VERDE", "Perdida de objeto": "CLAVE VERDE"
}
df_completo["ClaveEmergencia"] = df_completo["TipoEmergencia"].map(mapa_claves).fillna("CLAVE VERDE")

# Exportar archivo final
df_completo.to_csv('/content/drive/MyDrive/Colab Notebooks/dataset_final_estructurado.csv', index=False)
print("✔️ Archivo final generado como 'dataset_final_estructurado.csv'")







import pandas as pd
import re
from transformers import pipeline
from keybert import KeyBERT
from sentence_transformers import SentenceTransformer

# 1. Cargar datos
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado_1.csv')

# 2. Limpiar texto
def limpiar_texto(texto):
    texto = str(texto).lower()
    texto = re.sub(r'[^\w\s]', '', texto)
    return texto

df['TEXTO_LIMPIO'] = df['TEXTO_ALERTANTE'].apply(limpiar_texto)

# 3. Modelo de clasificación Zero-Shot (categoría de emergencia)
classifier = pipeline("zero-shot-classification", model="joeddav/xlm-roberta-large-xnli")

# Definir las posibles categorías de emergencia
categorias = ['robo', 'asalto', 'accidente', 'salud', 'violencia', 'incendio', 'amenaza', 'desmayo', 'persona perdida', 'emergencia médica']

# Clasificar cada texto
def clasificar_emergencia(texto):
    resultado = classifier(texto, candidate_labels=categorias)
    return resultado['labels'][0]  # etiqueta con mayor score

df['CATEGORIA_EMERGENCIA'] = df['TEXTO_LIMPIO'].apply(clasificar_emergencia)

# 4. Extraer palabras clave con KeyBERT
modelo_emb = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
kw_model = KeyBERT(model=modelo_emb)

def extraer_keywords(texto):
    keywords = kw_model.extract_keywords(texto, keyphrase_ngram_range=(1, 1), stop_words='spanish', top_n=5)
    return [kw[0] for kw in keywords]

df['PALABRAS_CLAVE'] = df['TEXTO_LIMPIO'].apply(extraer_keywords)

# 5. Guardar resultados
df[['TEXTO_ALERTANTE', 'CATEGORIA_EMERGENCIA', 'PALABRAS_CLAVE']].to_csv('/content/drive/MyDrive/Colab Notebooks/dataset_emergencias_procesado_1.csv', index=False)

print("✅ ¡Listo! Archivo guardado como 'dataset_emergencias_procesado_1.csv'")

import pandas as pd
import re
import torch
from transformers import pipeline, XLMRobertaTokenizer, XLMRobertaForSequenceClassification

# 1. Cargar el dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ecu911_alertantes_procesado_1.csv')

# Seleccionar una muestra aleatoria de 500 registros
df = df.sample(n=5, random_state=42).reset_index(drop=True)

# 2. Limpiar texto
def limpiar_texto(texto):
    texto = str(texto).lower()
    texto = re.sub(r'[^\w\s]', '', texto)
    return texto.strip()

df['TEXTO_LIMPIO'] = df['TEXTO_ALERTANTE'].apply(limpiar_texto)

# 3. Inicializar modelo Zero-Shot con GPU si está disponible
device = 0 if torch.cuda.is_available() else -1  # 0 para GPU, -1 para CPU

model_name = "joeddav/xlm-roberta-large-xnli"
tokenizer = XLMRobertaTokenizer.from_pretrained(model_name)
model = XLMRobertaForSequenceClassification.from_pretrained(model_name)

classifier = pipeline(
    "zero-shot-classification",
    model=model,
    tokenizer=tokenizer,
    device=device  # <--- ESTE CAMBIO ES CLAVE
)

# 4. Categorías
categorias = [
    "robo",
    "asalto",
    "violencia doméstica",
    "accidente de tránsito",
    "persona herida",
    "emergencia médica",
    "incendio",
    "amenaza con arma",
    "persona perdida",
    "pelea"
]

# 5. Clasificar
def clasificar_emergencia(texto):
    if not isinstance(texto, str) or texto.strip() == "":
        return "no_clasificado"
    resultado = classifier(texto, candidate_labels=categorias)
    return resultado['labels'][0]

# 6. Aplicar
df['CATEGORIA_EMERGENCIA'] = df['TEXTO_LIMPIO'].apply(clasificar_emergencia)

# 7. Guardar resultados
df[['TRA_ID', 'TEXTO_ALERTANTE', 'CATEGORIA_EMERGENCIA']].to_csv(
    '/content/drive/MyDrive/Colab Notebooks/dataset_emergencias_solo_categoria.csv', index=False
)

print("✅ Archivo generado: 'dataset_emergencias_solo_categoria.csv'")

import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm

# 📂 Ruta a tu archivo de entrada (reemplaza con el tuyo)
archivo_entrada = '/content/drive/MyDrive/Colab Notebooks/springer_zotero_import.csv'

# 📥 Leer archivo según tipo
if archivo_entrada.endswith('.csv'):
    df = pd.read_csv(archivo_entrada)
elif archivo_entrada.endswith('.xlsx'):
    df = pd.read_excel(archivo_entrada)
else:
    raise ValueError("Formato de archivo no soportado. Usa .csv o .xlsx")

# 🔍 Detectar columna de URL
url_column = 'ENLACE' if 'ENLACE' in df.columns else 'url'
if url_column not in df.columns:
    raise ValueError("No se encontró la columna 'ENLACE' o 'URL'.")

# 🧠 Función para extraer abstract desde la URL de SpringerLink
def extraer_abstract(url):
    try:
        headers = {'User-Agent': 'Mozilla/5.0'}
        r = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(r.text, "html.parser")
        abstract_section = soup.find("section", class_="Abstract")
        if abstract_section:
            return abstract_section.get_text(separator=" ", strip=True)
        else:
            return "No abstract encontrado"
    except Exception as e:
        return f"Error: {e}"

# ⚙️ Aplicar función a cada enlace
print("Extrayendo abstracts...")
df['ABSTRACT_EXTRAIDO'] = [extraer_abstract(url) for url in tqdm(df[url_column])]

# 💾 Guardar archivo final
archivo_salida = 'resultados_con_abstracts.xlsx'
df.to_excel(archivo_salida, index=False)
print(f"✅ Archivo guardado como: {archivo_salida}")

!pip install deep-translator pandas openpyxl

import pandas as pd
from deep_translator import GoogleTranslator

# Paso 1: Subir archivo
from google.colab import files
uploaded = files.upload()

# Paso 2: Cargar el archivo Excel (ajusta el nombre si es diferente)
df = pd.read_excel(next(iter(uploaded)))

# Paso 3: Traducir abstracts al español
def traducir_abstract(texto):
    try:
        return GoogleTranslator(source='auto', target='es').translate(texto)
    except Exception as e:
        return f"[ERROR DE TRADUCCIÓN]: {str(e)}"

df['ABSTRACT_ES'] = df['ABSTRACT'].apply(lambda x: traducir_abstract(x) if isinstance(x, str) else "")

# Paso 4: Clasificar con relevancia y justificación
def clasificar_articulo(row):
    titulo = str(row['TITULO']).lower()
    abstract = str(row['ABSTRACT']).lower()
    texto = f"{titulo} {abstract}"

    if not abstract.strip():
        return 0, "Sin resumen disponible."

    if any(term in texto for term in ["speech recognition", "asr", "spoken language understanding", "audio", "speech"]):
        if "spanish" in texto or "hispanic" in texto:
            if "lexical" in texto or "semantic" in texto:
                return 1, ""
            else:
                return 2, "Trata PLN en audio/habla en español, pero no se especifica enfoque léxico-semántico."
        elif "lexical" in texto or "semantic" in texto:
            return 2, "Se enfoca en aspectos léxico-semánticos del habla, pero no en español."
        else:
            return 2, "Trata PLN en modalidad de audio pero no aborda el español ni el desarrollo léxico-semántico claramente."
    elif "natural language processing" in texto and "audio" in texto:
        return 2, "Menciona PLN y audio, pero no especifica enfoque léxico-semántico ni idioma."

    return 0, "No aborda PLN, audio ni desarrollo léxico-semántico."

clasificaciones = df.apply(clasificar_articulo, axis=1)
df['RELEVANCIA'] = clasificaciones.apply(lambda x: x[0])
df['JUSTIFICACION'] = clasificaciones.apply(lambda x: x[1])

# Paso 5: Guardar archivo final
nombre_salida = "Scopus_traducido_clasificado.xlsx"
df.to_excel(nombre_salida, index=False)

# Paso 6: Descargar el archivo
files.download(nombre_salida)

!pip install deep-translator pandas openpyxl

import pandas as pd
from deep_translator import GoogleTranslator

# Paso 1: Subir archivo
from google.colab import files
uploaded = files.upload()

# Paso 2: Cargar el archivo Excel
df = pd.read_excel(next(iter(uploaded)))

# Paso 3: Traducir abstracts al español
def traducir_abstract(texto):
    try:
        return GoogleTranslator(source='auto', target='es').translate(texto)
    except Exception as e:
        return f"[ERROR DE TRADUCCIÓN]: {str(e)}"

df['ABSTRACT_ES'] = df['ABSTRACT'].apply(lambda x: traducir_abstract(x) if isinstance(x, str) else "")

# Paso 4: Clasificar con relevancia según objetivos, pregunta y cadena
def clasificar_articulo(row):
    titulo = str(row['TITULO']).lower()
    abstract = str(row['ABSTRACT']).lower()
    texto = f"{titulo} {abstract}"

    if not abstract.strip():
        return 0, "Sin resumen disponible."

    # Coincidencia completa con la cadena de búsqueda y el enfoque léxico-semántico
    if all(term in texto for term in ["language model", "acoustic model", "speech recognition", "spanish"]):
        if any(t in texto for t in ["lexical", "semantic", "meaning", "understanding"]):
            return 1, "Coincide con la cadena de búsqueda y aborda desarrollo léxico-semántico."
        else:
            return 2, "Coincide con la cadena de búsqueda, pero no se especifica desarrollo léxico-semántico."

    # Coincidencia parcial con enfoque en voz o audio
    if any(term in texto for term in ["speech recognition", "asr", "spoken language understanding", "audio", "speech"]):
        if "spanish" in texto:
            if any(t in texto for t in ["lexical", "semantic", "meaning", "understanding"]):
                return 1, "Habla de PLN en español con enfoque léxico-semántico."
            else:
                return 2, "Está en español y trata voz/audio, pero no menciona desarrollo léxico-semántico."
        elif any(t in texto for t in ["lexical", "semantic", "meaning", "understanding"]):
            return 2, "Trata aspectos léxico-semánticos en voz, pero no en español."
        else:
            return 2, "Relaciona PLN y voz/audio, pero no cumple con el enfoque léxico-semántico ni idioma."

    # PLN general con audio
    elif "natural language processing" in texto and "audio" in texto:
        return 2, "Menciona PLN y audio, pero no especifica desarrollo léxico-semántico ni español."

    return 0, "No aborda PLN en audio, ni desarrollo léxico-semántico, ni español."

# Aplicar clasificación
clasificaciones = df.apply(clasificar_articulo, axis=1)
df['RELEVANCIA'] = clasificaciones.apply(lambda x: x[0])
df['JUSTIFICACION'] = clasificaciones.apply(lambda x: x[1])

# Paso 5: Guardar archivo final
nombre_salida = "articulos_clasificados_wos.xlsx"
df.to_excel(nombre_salida, index=False)

# Paso 6: Descargar archivo
files.download(nombre_salida)